mainSections = ["posts"]
featuredImageField = "image"
rssFullContent = true
favicon = "/favicon.ico"

[footer]
since = 2024
customText = ""

[dateFormat]
published = "2006/01/02"
lastUpdated = "2006/01/02 15:04"

[sidebar]
emoji = "ğŸ¥”"
subtitle = "ã‚¹ãƒãƒ›ã¨ã‹ãƒãƒ¼ãƒ‰ç³»ã®ã‚‚ã®ãŒå¥½ãã§ã™"
[sidebar.avatar]
enabled = true
local = true
src = "img/icon_j.jpg"

[article]
math = false
toc = true
readingTime = true
[article.license]
enabled = false
default = ""

[comments]
enabled = false
provider = ""

[widgets]

[[widgets.homepage]]
type = "search"

[[widgets.homepage]]
type = "archives"
params = { limit = 5 }

[[widgets.homepage]]
type = "categories"
params = { limit = 10 }

[[widgets.homepage]]
type = "tag-cloud"
params = { limit = 10 }

[[widgets.page]]
type = "toc"

[opengraph]
[opengraph.twitter]
site = "@Jyaga_bee"
card = "summary_large_image"

[defaultImage]
[defaultImage.opengraph]
enabled = false
local = false
src = ""

[colorScheme]
toggle = true
default = "auto"

[imageProcessing]
[imageProcessing.cover]
enabled = true
[imageProcessing.content]
enabled = true